@baseUrl = http://localhost:3000

### List all events
GET {{baseUrl}}/events

### Get a single event by id
GET {{baseUrl}}/events/1

### Get a non-existent event (should 404)
GET {{baseUrl}}/events/99

### Create a new event
POST {{baseUrl}}/events
Content-Type: application/json

{
  "name": "Poetry Slam"
}


### Update an event
PUT {{baseUrl}}/events/1
Content-Type: application/json

{
  "name": "Rust Meetup (Updated)"
}

### Delete an event
DELETE {{baseUrl}}/events/2

### Confirm it's gone
GET {{baseUrl}}/events